[project]
name = "bioext"
version = "0.1.0"
description = "Helper functions for bio-ext pipelines"
authors = [
    { name = "Joe Zhang", email = "joe.zhang@gstt.nhs.uk" },
    { name = "Lawrence Adams", email = "lawrence.adams@gstt.nhs.uk" },
]
readme = "README.md"
requires-python = ">=3.11.2"
dependencies = [
    "mlflow[extras]",
    "boto3",
    "requests",
    "elasticsearch",
    "elasticsearch-dsl",
    "elastic-transport",
    "doccano-client",
    "requests-toolbelt==1.0.0", # Required for doccano-client
    "vcrpy==4.4.0",             # Required for doccano-client
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/bioext"]