services:
  doccano:
    image: doccano/doccano:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data/doccano:/data
    environment:
      - ADMIN_USERNAME="${DOCCANO_ADMIN_USERNAME}"
      - ADMIN_PASSWORD="${DOCCANO_ADMIN_PASSWORD}"
      - ADMIN_EMAIL="${DOCCANO_ADMIN_EMAIL}"
      - DJANGO_DB_ENGINE=django.db.backends.sqlite3
      - DJANGO_DB_NAME=/data/doccano.sqlite3
    command: ["/doccano/tools/run.sh", "webserver"]
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./data/mlflow:/mlflow/data
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlflow/data/mlflow.db #use sqlite in mounted volume for metadata
      - MLFLOW_ARTIFACT_ROOT=s3://mlflow-artifacts #use s3 type storage instead of local dir
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY}
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000      
    command: mlflow server --host 0.0.0.0 --port 5000
    restart: unless-stopped
    depends_on:
      - minio
      
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    restart: unless-stopped