services:
  doccano:
    image: doccano/doccano:1.8.4
    container_name: bioextdoccano
    networks:
      - bioext_network    
    ports:
      - "8000:8000"
    volumes:
      - doccano_data:/data
    environment:
      - ADMIN_USERNAME=${DOCCANO_ADMIN_USERNAME}
      - ADMIN_PASSWORD=${DOCCANO_ADMIN_PASSWORD}
      - ADMIN_EMAIL=${DOCCANO_ADMIN_EMAIL}
      - DJANGO_DB_ENGINE=django.db.backends.sqlite3
      - DJANGO_DB_NAME=/data/doccano.sqlite3
    command: ["/doccano/tools/run.sh", "webserver"]
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G      
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    container_name: bioextminio
    networks:
      - bioext_network    
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: ["server", "/data", "--console-address", ":9001", "--address", ":9000"]
    deploy: 
      resources:
        limits:
          cpus: '2'
          memory: 8G      
    restart: unless-stopped
    
  mlflow:
    image: drjzhn/mlflow-boto:v2.17.0
    container_name: bioextmlflow
    networks:
      - bioext_network    
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow/data
    environment:
      # - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
      - MLFLOW_S3_IGNORE_TLS=true
      - AWS_DEFAULT_REGION=minio
      # - MLFLOW_ARTIFACT_ROOT=${MLFLOW_ARTIFACT_ROOT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MLFLOW_LOGGING_LEVEL=DEBUG
    command: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:///mlflow/data/mlflow.db", "--artifacts-destination", "s3://mlflow-artifacts", "--serve-artifacts"]
    depends_on:
      - minio
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G            
    restart: unless-stopped

volumes:
  mlflow_data:
  minio_data:
  doccano_data:

networks:
  bioext_network:
    name: bioext_network