services:
  doccano:
    image: doccano/doccano:latest
    container_name: doccano_bioext
    ports:
      - "8000:8000"
    volumes:
      - doccano_data:/data
    environment:
      - ADMIN_USERNAME=${DOCCANO_ADMIN_USERNAME}
      - ADMIN_PASSWORD=${DOCCANO_ADMIN_PASSWORD}
      - ADMIN_EMAIL=${DOCCANO_ADMIN_EMAIL}
      - DJANGO_DB_ENGINE=django.db.backends.sqlite3
      - DJANGO_DB_NAME=/data/doccano.sqlite3
    command: ["/doccano/tools/run.sh", "webserver"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 60s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G      
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio_bioext
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: ["server", "/data", "--console-address", ":9001", "--address", ":9000"]
    deploy: 
      resources:
        limits:
          cpus: '2'
          memory: 8G      
    restart: unless-stopped
    
  mlflow:
    image: drjzhn/mlflow-boto:latest
    container_name: mlflow_bioext
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow/data
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
      - MLFLOW_ARTIFACT_ROOT=${MLFLOW_ARTIFACT_ROOT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:///mlflow/data/mlflow.db", "--default-artifact-root", "s3://mlflow-artifacts"]
    depends_on:
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 60s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G            
    restart: unless-stopped

volumes:
  mlflow_data:
  minio_data:
  doccano_data: